# Generated by Django 4.1.1 on 2022-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=34)),
            ],
        ),
    ]
