# Generated by Django 4.1.1 on 2022-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employemodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
