# Generated by Django 4.1.1 on 2022-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0002_alter_employemodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employemodel',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employemodel',
            name='work_experience',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
