# Generated by Django 4.1.1 on 2022-09-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0003_employemodel_address_employemodel_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employemodel',
            name='Project',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employemodel',
            name='Qualification',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
